parameters:
    version:
        type: string
        default: 2.18.5

steps:
    - run:
          name: Install PHP CS Fixer << parameters.version >>
          command: >
            sudo wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v<< parameters.version >>/php-cs-fixer.phar -O /usr/local/bin/php-cs-fixer;

            sudo chmod +x /usr/local/bin/php-cs-fixer
