parameters:
    directory:
        type: string

steps:
    - run:
          name: Run PHP CS Fixer
          command: >
              cd << parameters.directory >> && php-cs-fixer fix --dry-run --allow-risky yes --diff --config=.php_cs
