executor: php/default
working_directory: /home/circleci/redirectionio
steps:
    - checkout_with_cache
    - install-php-cs-fixer
    - php-cs-fixer:
          directory: << pipeline.parameters.php_sdk_directory >>
